import os   

BOT_TOKEN = os.getenv("BOT_TOKEN")

CHANNEL_LINK = "https://t.me/PROFESSORXZAMINHACKER"
DEVELOPER_ID = "@SIGMAXZAMIN"
BOT_USERNAME = "@FileExecutionBot"
BOT_NAME = "TEXT TO FILES GENERATOR BOT"
