import logging, os
from aiogram import Bot, Dispatcher, executor, types
from aiogram.contrib.fsm_storage.memory import MemoryStorage
from aiogram.dispatcher import FSMContext
from aiogram.dispatcher.filters.state import State, StatesGroup

from config import BOT_TOKEN, CHANNEL_LINK, DEVELOPER_ID, BOT_USERNAME, BOT_NAME

logging.basicConfig(level=logging.INFO)

bot = Bot(BOT_TOKEN, parse_mode="HTML")
dp = Dispatcher(bot, storage=MemoryStorage())

# ================= STATES =================
class FileFlow(StatesGroup):
    waiting_text = State()
    waiting_name = State()
    waiting_format = State()

# ================= KEYBOARDS =================
def main_kb():
    kb = types.ReplyKeyboardMarkup(resize_keyboard=True)
    kb.add("📝 Text → File", "🌍 Translate Text")
    kb.add("📢 Channel", "👨‍💻 Developer")
    return kb

def format_kb():
    kb = types.InlineKeyboardMarkup(row_width=2)
    kb.add(
        types.InlineKeyboardButton("📄 TXT", callback_data="txt"),
        types.InlineKeyboardButton("🐍 PY", callback_data="py"),
        types.InlineKeyboardButton("🌐 HTML", callback_data="html"),
        types.InlineKeyboardButton("🧩 JSON", callback_data="json"),
    )
    return kb

# ================= START =================
@dp.message_handler(commands=["start"])
async def start(message: types.Message):
    name = message.from_user.first_name
    await message.answer(
f"""━━━━━━━━━━━━━━━━━━━━━━━
💀 <b>{BOT_NAME}</b> 💀
━━━━━━━━━━━━━━━━━━━━━━━

👑 Welcome <b>{name}</b>

➤ Paste text  
➤ Name your file  
➤ Choose format  

❝ From idea to file — instantly ❞ ⚡
━━━━━━━━━━━━━━━━━━━━━━━
""",
reply_markup=main_kb()
)

# ================= CHANNEL =================
@dp.message_handler(lambda m: m.text == "📢 Channel")
async def channel(message: types.Message):
    await message.answer(
"""━━━━━━━━━━━━━━━━━━━━━━━
📢 <b>OFFICIAL CHANNEL</b>

Updates • Features • Power tools  
Everything first — only here ⚡

👉 <b>Join now:</b>
https://t.me/PROFESSORXZAMINHACKER
━━━━━━━━━━━━━━━━━━━━━━━
""",
disable_web_page_preview=True
)

# ================= DEVELOPER =================
@dp.message_handler(lambda m: m.text == "👨‍💻 Developer")
async def developer(message: types.Message):
    await message.answer(f"👨‍💻 Developer: {DEVELOPER_ID}")

# ================= TEXT → FILE FLOW =================
@dp.message_handler(lambda m: m.text == "📝 Text → File")
async def start_file_flow(message: types.Message):
    await FileFlow.waiting_text.set()
    await message.answer(
"""━━━━━━━━━━━━━━━━━━━━━━━
✍️ <b>SEND YOUR TEXT</b>

➤ Paste code or normal text  
➤ No limits • No filters  

❝ Words become files here ❞ ⚡
━━━━━━━━━━━━━━━━━━━━━━━
""",
reply_markup=types.ReplyKeyboardRemove()
)

@dp.message_handler(state=FileFlow.waiting_text)
async def get_text(message: types.Message, state: FSMContext):
    await state.update_data(text=message.text)
    await FileFlow.waiting_name.set()
    await message.answer(
"""━━━━━━━━━━━━━━━━━━━━━━━
📛 <b>SEND FILE NAME</b>

➤ Without extension  
➤ Example: <code>index</code>

❝ Name it. Own it. ❞
━━━━━━━━━━━━━━━━━━━━━━━
"""
)

@dp.message_handler(state=FileFlow.waiting_name)
async def get_name(message: types.Message, state: FSMContext):
    await state.update_data(name=message.text)
    await FileFlow.waiting_format.set()
    await message.answer(
"🧩 <b>CHOOSE OUTPUT FORMAT</b>",
reply_markup=format_kb()
)

@dp.callback_query_handler(state=FileFlow.waiting_format)
async def generate_file(call: types.CallbackQuery, state: FSMContext):
    data = await state.get_data()
    text = data["text"]
    name = data["name"]
    ext = call.data

    filename = f"{name}.{ext}"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(
f"""# Generated by {BOT_NAME}
# Bot: {BOT_USERNAME}
# Developer: {DEVELOPER_ID}

{text}
"""
        )

    await call.message.answer_document(
        open(filename, "rb")
    )

    await call.message.answer(
f"""━━━━━━━━━━━━━━━━━━━━━━━
🎉 <b>FILE CREATED SUCCESSFULLY</b>

Your file is ready & delivered 📁  
Clean • Accurate • Ready to use  

🔁 Want to create another file?

➤ Click 📝 Text → File  
➤ Send new text  
➤ Name the file  
➤ Choose format  

❝ One idea. Unlimited files. ❞ ⚡

👨‍💻 Developer: {DEVELOPER_ID}
🤖 Bot: {BOT_USERNAME}
━━━━━━━━━━━━━━━━━━━━━━━
""",
reply_markup=main_kb()
    )

    os.remove(filename)
    await state.finish()

# ================= RUN =================
if __name__ == "__main__":
    executor.start_polling(dp, skip_updates=True)
