import logging
import os
from aiogram import Bot, Dispatcher, executor, types

# ================= CONFIG =================
BOT_TOKEN = os.getenv("BOT_TOKEN")  # Railway variable
CHANNEL_LINK = "https://t.me/PROFESSORXZAMINHACKER"
DEVELOPER_ID = "@SIGMAXZAMIN"

logging.basicConfig(level=logging.INFO)

bot = Bot(token=BOT_TOKEN, parse_mode="HTML")
dp = Dispatcher(bot)

# user state memory
user_mode = {}

# ================= KEYBOARDS =================
def main_kb():
    kb = types.InlineKeyboardMarkup(row_width=2)
    kb.add(
        types.InlineKeyboardButton("📄 Text → File", callback_data="text_file"),
        types.InlineKeyboardButton("🌍 Translate Text", callback_data="translate"),
    )
    kb.add(
        types.InlineKeyboardButton("📚 Languages", callback_data="languages")
    )
    kb.add(
        types.InlineKeyboardButton("📢 Channel", url=CHANNEL_LINK),
        types.InlineKeyboardButton("👨‍💻 Developer", url=f"https://t.me/{DEVELOPER_ID[1:]}")
    )
    return kb

# ================= START =================
@dp.message_handler(commands=["start"])
async def start_cmd(message: types.Message):
    name = message.from_user.first_name

    text = f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💀 <b>TEXT TO FILES GENERATOR BOT</b> 💀
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👑 Welcome <b>{name}</b>

This is not a normal generator.
This is your <b>code weapon</b> ⚔️

➤ Paste text  
➤ Choose language  
➤ Get ready-to-use files  

❝ From idea to file — instantly ❞ ⚡

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
    await message.answer(text, reply_markup=main_kb())

# ================= CALLBACKS =================
@dp.callback_query_handler(lambda c: c.data == "text_file")
async def text_file_cb(call: types.CallbackQuery):
    user_mode[call.from_user.id] = "text_file"
    await call.message.reply(
        "✍️ <b>Text → File Mode Activated</b>\n\n"
        "➤ Now send the text you want to convert into a file.\n"
        "➤ File will be generated instantly."
    )
    await call.answer()

@dp.callback_query_handler(lambda c: c.data == "translate")
async def translate_cb(call: types.CallbackQuery):
    user_mode[call.from_user.id] = "translate"
    await call.message.reply(
        "🌍 <b>Translate Mode Activated</b>\n\n"
        "➤ Send text you want to translate.\n"
        "➤ Language support coming soon."
    )
    await call.answer()

@dp.callback_query_handler(lambda c: c.data == "languages")
async def languages_cb(call: types.CallbackQuery):
    await call.message.reply(
        "📚 <b>Supported Output Types</b>\n\n"
        "• TXT\n"
        "• PY (Python)\n"
        "• HTML\n"
        "• JSON\n\n"
        "More coming soon ⚡"
    )
    await call.answer()

# ================= MESSAGE HANDLER =================
@dp.message_handler()
async def handle_text(message: types.Message):
    mode = user_mode.get(message.from_user.id)

    if mode == "text_file":
        text = message.text

        file_path = "output.txt"
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(text)

        await message.reply_document(
            open(file_path, "rb"),
            caption="✅ <b>Your file is ready!</b>\nGenerated by Text to Files Generator Bot"
        )

        user_mode.pop(message.from_user.id, None)

    elif mode == "translate":
        await message.reply(
            "⚠️ Translation engine will be added next.\n"
            "For now, use Text → File feature."
        )
        user_mode.pop(message.from_user.id, None)

    else:
        await message.reply(
            "⚠️ Please select an option from below first.",
            reply_markup=main_kb()
        )

# ================= RUN =================
if __name__ == "__main__":
    executor.start_polling(dp, skip_updates=True)
