import logging
import os
from aiogram import Bot, Dispatcher, executor, types
from aiogram.dispatcher import FSMContext
from aiogram.dispatcher.filters.state import State, StatesGroup
from aiogram.contrib.fsm_storage.memory import MemoryStorage

# CONFIG
BOT_TOKEN = os.getenv("BOT_TOKEN")
CHANNEL_LINK = "https://t.me/PROFESSORXZAMINHACKER"
DEVELOPER_ID = "@SIGMAXZAMIN"
BOT_NAME = "TEXT TO FILES GENERATOR BOT"

logging.basicConfig(level=logging.INFO)

bot = Bot(token=BOT_TOKEN, parse_mode="HTML")
dp = Dispatcher(bot, storage=MemoryStorage())

# STATES
class FileState(StatesGroup):
    waiting_text = State()
    waiting_filename = State()
    waiting_format = State()

# KEYBOARDS
def main_kb():
    kb = types.ReplyKeyboardMarkup(resize_keyboard=True)
    kb.add("📝 Text → File", "🌐 Translate Text")
    kb.add("📢 Channel", "👨‍💻 Developer")
    return kb

def format_kb():
    kb = types.InlineKeyboardMarkup(row_width=2)
    kb.add(
        types.InlineKeyboardButton("📄 TXT", callback_data="txt"),
        types.InlineKeyboardButton("🐍 PY", callback_data="py"),
        types.InlineKeyboardButton("🌐 HTML", callback_data="html"),
        types.InlineKeyboardButton("🧩 JSON", callback_data="json")
    )
    return kb

# START
@dp.message_handler(commands=["start"])
async def start(message: types.Message):
    name = message.from_user.first_name
    await message.answer(
        f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💀 <b>{BOT_NAME}</b> 💀
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👑 Welcome <b>{name}</b>

This is not a normal generator.
This is your <b>code weapon</b> ⚔️

➤ Text → Real Files  
➤ Multiple Languages  
➤ Ready-to-use output  

❝ From idea to file — instantly ❞ ⚡

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""",
        reply_markup=main_kb()
    )

# TEXT TO FILE
@dp.message_handler(lambda m: m.text == "📝 Text → File")
async def text_to_file(message: types.Message):
    await FileState.waiting_text.set()
    await message.answer(
        """
━━━━━━━━━━━━━━━━━━━━━━━
✍️ <b>SEND YOUR TEXT</b>

➤ Paste code or plain text  
➤ No limits, no filters  
➤ Your content stays private  

❝ Words become files here ❞ ⚡
━━━━━━━━━━━━━━━━━━━━━━━
"""
    )

@dp.message_handler(state=FileState.waiting_text)
async def get_text(message: types.Message, state: FSMContext):
    await state.update_data(text=message.text)
    await FileState.waiting_filename.set()
    await message.answer(
        """
━━━━━━━━━━━━━━━━━━━━━━━
📛 <b>SEND FILE NAME</b>

➤ Without extension  
➤ Example: <code>index</code>  

❝ Name it. Own it. ❞
━━━━━━━━━━━━━━━━━━━━━━━
"""
    )

@dp.message_handler(state=FileState.waiting_filename)
async def get_filename(message: types.Message, state: FSMContext):
    await state.update_data(filename=message.text)
    await FileState.waiting_format.set()
    await message.answer(
        "🧩 <b>CHOOSE OUTPUT FORMAT</b>",
        reply_markup=format_kb()
    )

@dp.callback_query_handler(state=FileState.waiting_format)
async def make_file(call: types.CallbackQuery, state: FSMContext):
    data = await state.get_data()
    text = data["text"]
    filename = data["filename"]
    ext = call.data

    content = f"""# Generated by {BOT_NAME}
# Developer: {DEVELOPER_ID}
# Channel: {CHANNEL_LINK}

{text}
"""

    file_path = f"{filename}.{ext}"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    await call.message.answer_document(
        open(file_path, "rb"),
        caption="✅ <b>Your file is ready!</b>"
    )

    await call.message.answer(
        f"""
━━━━━━━━━━━━━━━━━━━━━━━
🎉 <b>DONE!</b>

Your file is ready 📄  
Simple • Fast • Reliable  

Use it anywhere — no edits needed.

👨‍💻 Developer: {DEVELOPER_ID}
━━━━━━━━━━━━━━━━━━━━━━━
"""
    )

    os.remove(file_path)
    await state.finish()

# EXTRA BUTTONS
@dp.message_handler(lambda m: m.text == "📢 Channel")
async def channel(message: types.Message):
    await message.answer(CHANNEL_LINK)

@dp.message_handler(lambda m: m.text == "👨‍💻 Developer")
async def dev(message: types.Message):
    await message.answer(DEVELOPER_ID)

# RUN
if __name__ == "__main__":
    executor.start_polling(dp, skip_updates=True)
